# Generated by Django 6.0.5 on 2026-06-11 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('bachillerato', 'Bachillerato')], max_length=50)),
                ('jornada', models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=50)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['nivel', 'nombre_grado'],
                'unique_together': {('nombre_grado', 'nivel', 'jornada')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('intensidad_horaria', models.PositiveIntegerField(default=0)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academic.grado')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre_materia'],
            },
        ),
    ]
