# Generated by Django 6.0.5 on 2026-06-11 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=20)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic.grado')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic.materia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'unique_together': {('id_grado', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
