# Generated by Django 6.0.5 on 2026-06-11 02:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1', 'Primer Período'), ('2', 'Segundo Período'), ('3', 'Tercer Período'), ('4', 'Cuarto Período')], max_length=20)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='people.estudiante')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.materia')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('id_estudiante', 'id_materia', 'periodo')},
            },
        ),
    ]
