# Generated by Django 6.0.5 on 2026-06-11 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academic.materia')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='people.profesor')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
